version: '2'
services:
    mariadb:
        image: mariadb:10.7.3
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db_name
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_pwd
        ports:
            - "8082:3306"

    webapp:
        build:
            context: ./
        volumes:
            - ./src/php:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - mariadb
