version: '2'
services:
    ddagent:
        image: datadog/agent:latest
        environment:
            - DD_SITE=datadoghq.eu
            - DD_API_KEY=${DATADOG_API_KEY}
            - DD_APM_ENABLED=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc/:/host/proc/:ro
            - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

    mariadb:
        image: mariadb:10.7.3
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=db_name
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=db_pwd
        ports:
            - "8082:3306"

    webapp:
        build:
            context: ./
        environment:
            - DD_AGENT_HOST=ddagent
            - DD_SERVICE=my-php-app
            - DD_ENV=dev
            - DD_VERSION=1.0
        volumes:
            - ./src/php:/var/www/html
        ports:
            - 8000:80
        depends_on:
            - mariadb
